Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.ssh.username = 'vagrant'
  #config.ssh.password = 'vagrant'
  config.ssh.insert_key = false
  #config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 9000, host: 9000
  config.vm.network :forwarded_port, guest: 9080, host: 9080
  config.vm.network :forwarded_port, guest: 9090, host: 9090
  config.vm.network :forwarded_port, guest: 9443, host: 9443
  config.vm.network :forwarded_port, guest: 9091, host: 9091
  config.vm.define "centos-apisix"
  config.vm.provision "shell", path: "./apisix_install.sh"
  config.vm.provider "virtualbox" do |v|
     v.customize ["modifyvm", :id, "--memory", "2048"]
     v.customize ["modifyvm", :id, "--cpus", "2"]
  end
end
