Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"  
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = false
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 21000, host: 21000

  config.vm.provider "virtualbox" do |v|
     v.customize ["modifyvm", :id, "--memory", "8048"]
     v.customize ["modifyvm", :id, "--cpus", "2"]
  
     config.vm.provider :virtualbox do |vb|
       vb.name = "OpsMx-Spinnaker"
     end
  end
  config.vm.provision "shell", path: "opsmx-install-spinnaker.sh"
end

