Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = false
  #config.vm.network :forwarded_port, guest: 80, host: 80
  config.vm.network :forwarded_port, guest: 8088, host: 8088
  config.vm.network :forwarded_port, guest: 50070, host: 50070
  config.vm.network :forwarded_port, guest: 8998, host: 8998
  config.vm.network :forwarded_port, guest: 9000, host: 9000
  config.vm.network :forwarded_port, guest: 9093, host: 9093
  config.vm.network :forwarded_port, guest: 4040, host: 4040
  config.vm.provision "shell", path: "./hadoop_install.sh"
  config.vm.provision "shell", path: "./spark_install.sh"

  config.vm.provider "virtualbox" do |v|
     v.customize ["modifyvm", :id, "--memory", "4048"]
     v.customize ["modifyvm", :id, "--cpus", "2"]
	 v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
	 v.customize ["modifyvm", :id, "--nictype1", "virtio"]
	 v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]


  end
end