Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.ssh.username = 'vagrant'
  #config.ssh.password = 'vagrant'
  config.ssh.insert_key = false
  config.vm.network :forwarded_port, guest: 9093, host: 9093
  config.vm.define "ubuntu-flume"

  config.vm.provider "virtualbox" do |v|
     v.customize ["modifyvm", :id, "--memory", "4048"]
     v.customize ["modifyvm", :id, "--cpus", "2"]
  end
end

