Vagrant.configure("2") do |config|
  config.vm.box = "mwrock/Windows2016"
  config.vm.provider "virtualbox" do |v|
     v.customize ["modifyvm", :id, "--memory", "3048"]
     v.customize ["modifyvm", :id, "--cpus", "2"]
  end
end